spring.application.name=app-books

server.port=9090
# Configuración de base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/distribuidaG
spring.datasource.username=postgres
spring.datasource.password=1234

# JPA (opcional si usas Spring Data JPA)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Configuración de Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration


# Configuración de Consul
spring.cloud.consul.host=localhost
spring.cloud.consul.port=8500
spring.cloud.consul.discovery.register=true
spring.cloud.consul.discovery.deregister=true
spring.cloud.consul.discovery.instance-id=app-books-${random.int}
spring.cloud.consul.discovery.service-name=app-books
spring.cloud.consul.discovery.health-check-path=/ping
spring.cloud.consul.discovery.health-check-interval=10s


# Etiquetas para Traefik
spring.cloud.consul.discovery.tags=\
traefik.enable=true,\
traefik.http.routers.app-books.rule=PathPrefix(`/app-books`),\
traefik.http.routers.app-books.middlewares=strip-prefix-books,\
traefik.http.middlewares.strip-prefix-books.stripprefix.prefixes=/app-books