spring.application.name=app-authors
server.port=8080
# Configuración de base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=1948

#Configuracion de hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Consul
# Configuración de Consul
spring.cloud.consul.host=localhost
spring.cloud.consul.port=8500
spring.cloud.consul.discovery.service-name=app-authors
spring.cloud.consul.discovery.instance-id=${spring.application.name}:${server.port}
spring.cloud.consul.discovery.health-check-path=/actuator/health
spring.cloud.consul.discovery.health-check-interval=15s

# Tags para Traefik
spring.cloud.consul.discovery.tags[0]=traefik.enable=true
spring.cloud.consul.discovery.tags[1]=traefik.http.routers.app-authors.rule=PathPrefix(`/app-authors`)
spring.cloud.consul.discovery.tags[2]=traefik.http.routers.app-authors.middlewares=strip-prefix-authors
spring.cloud.consul.discovery.tags[3]=traefik.http.middlewares.strip-prefix-authors.stripPrefix.prefixes=/app-authors